// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyyzhrRSQp1hmXkiKP3QAs7-vyPIbKfMQ',
    appId: '1:84494741816:web:7f66234fd19a228027d1cd',
    messagingSenderId: '84494741816',
    projectId: 'flutter-blog-app-ff10f',
    authDomain: 'flutter-blog-app-ff10f.firebaseapp.com',
    storageBucket: 'flutter-blog-app-ff10f.appspot.com',
    measurementId: 'G-3RJ9P45DXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdbDou4K4QsjxuEkHhXfpe3_dPk9bcCVM',
    appId: '1:84494741816:android:4ea51917cbcdeeab27d1cd',
    messagingSenderId: '84494741816',
    projectId: 'flutter-blog-app-ff10f',
    storageBucket: 'flutter-blog-app-ff10f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGOO0EOfGlgRk1MsRt_ayU4C6F4CnhtC0',
    appId: '1:84494741816:ios:c288a3d29523eacd27d1cd',
    messagingSenderId: '84494741816',
    projectId: 'flutter-blog-app-ff10f',
    storageBucket: 'flutter-blog-app-ff10f.appspot.com',
    iosBundleId: 'com.example.flutterBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGOO0EOfGlgRk1MsRt_ayU4C6F4CnhtC0',
    appId: '1:84494741816:ios:c288a3d29523eacd27d1cd',
    messagingSenderId: '84494741816',
    projectId: 'flutter-blog-app-ff10f',
    storageBucket: 'flutter-blog-app-ff10f.appspot.com',
    iosBundleId: 'com.example.flutterBlogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyyzhrRSQp1hmXkiKP3QAs7-vyPIbKfMQ',
    appId: '1:84494741816:web:4a18b4472be3a86b27d1cd',
    messagingSenderId: '84494741816',
    projectId: 'flutter-blog-app-ff10f',
    authDomain: 'flutter-blog-app-ff10f.firebaseapp.com',
    storageBucket: 'flutter-blog-app-ff10f.appspot.com',
    measurementId: 'G-FQB846GW4K',
  );
}
